[package]
name = "rustyScience"
version = "0.1.0-alpha"
edition = "2024"
license = "MIT"
license-file = "LICENSE"

[dependencies]
rand = "0.9.0-alpha.2"
num = "0.4"

[dev-dependencies]
serde = { version = "1.0.214", features = ["derive"] }
csv = "1.3.0"
