[package]
name = "rusty_science"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"
num = "0.4"
num-traits = "0.2"

[dev-dependencies]
serde = { version = "1.0.214", features = ["derive"] }
csv = "1.3.0"
