[package]
name = "rusty_science"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"
num = "0.4"
num-traits = "0.2"
plotters = { version = "0.3.7", optional = true }

[features]
graphing = ["plotters"]
